CREATE TABLE IF NOT EXISTS aggregate (
    id VARCHAR(64) PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    version INTEGER NOT NULL,
    data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS event (
    id SERIAL PRIMARY KEY,
    type VARCHAR(64) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);
